# Generated by Django 5.2.1 on 2025-05-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="tipo",
            field=models.CharField(
                choices=[("aluno", "Aluno"), ("professor", "Professor")], max_length=10
            ),
        ),
    ]
