from .user_form import CustomUserCreationForm, CustomAuthenticationForm
from .aluno_form import PerfilAlunoForm
from .professor_form import PerfilProfessorForm
from .area_conhecimento_form import AreaConhecimentoForm